import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../",
);

export default {
  projectRoot,
  defaultEnvProfile: "e2e",
  envProfiles: {
    e2e: [".env.api.e2e.local", ".env.e2e.local"],
    dev: [".env.api.local", ".env.local"],
    prod: [".env.api.prod.local", ".env.prod.local"],
  },
  snapshotsDir: "scripts/admin-utils/data_snapshots/snapshots",
  logFile: "last-run.json",
  auth: {
    enabled: true,
    file: "auth-users.json",
    restoreUsers: true,
    restorePassword: "RestoredSnapshot!ChangeMe1",
  },
  tables: [
    { name: "admins", orderBy: ["email"], conflictColumns: ["email"] },
    { name: "profiles", orderBy: ["id"], conflictColumns: ["id"] },
    { name: "workspaces", orderBy: ["id"], conflictColumns: ["id"] },
    { name: "workspace_memberships", orderBy: ["workspace_id", "user_id"], conflictColumns: ["id"] },
    { name: "workspace_module_roles", orderBy: ["workspace_id", "user_id", "module_id"], conflictColumns: ["id"] },
    { name: "workspace_files", orderBy: ["storage_bucket", "storage_key"], conflictColumns: ["id"] },
    { name: "ai_provider_profiles", orderBy: ["created_at", "id"], conflictColumns: ["id"] },
    { name: "ai_prompt_profiles", orderBy: ["created_at", "id"], conflictColumns: ["id"] },
    { name: "extension_api_keys", orderBy: ["created_at", "id"], conflictColumns: ["id"] },
    { name: "extension_api_key_quota_events", orderBy: ["api_key_id", "created_at", "id"], conflictColumns: ["id"] },
    { name: "extension_users", orderBy: ["user_id"], conflictColumns: ["user_id"] },
    { name: "extension_api_key_users", orderBy: ["api_key_id", "extension_user_id"], conflictColumns: ["api_key_id", "extension_user_id"] },
    { name: "extension_generation_requests", orderBy: ["api_key_id", "created_at", "id"], conflictColumns: ["id"] },
    { name: "extension_generation_events", orderBy: ["request_id", "created_at", "id"], conflictColumns: ["id"] },
    { name: "extension_errors", orderBy: ["created_at", "id"], conflictColumns: ["id"] },
  ],
  restore: {
    deleteOrder: [
      "extension_errors",
      "extension_generation_events",
      "extension_generation_requests",
      "extension_api_key_users",
      "extension_users",
      "extension_api_key_quota_events",
      "extension_api_keys",
      "ai_prompt_profiles",
      "ai_provider_profiles",
      "admins",
      "workspace_module_roles",
      "workspace_files",
      "workspace_memberships",
      "workspaces",
      "profiles",
    ],
    insertOrder: [
      "admins",
      "profiles",
      "workspaces",
      "workspace_memberships",
      "workspace_module_roles",
      "workspace_files",
      "ai_provider_profiles",
      "ai_prompt_profiles",
      "extension_api_keys",
      "extension_api_key_quota_events",
      "extension_users",
      "extension_api_key_users",
      "extension_generation_requests",
      "extension_generation_events",
      "extension_errors",
    ],
  },
  storage: {
    enabled: true,
    bucketsFromEnv: ["STORAGE_S3_BUCKET"],
    listPageSize: 100,
    saveObjectBodies: false,
  },
};
